### ISSUE TITLE
some errors following readme

### ISSUE THREAD

**Issue by samvloeberghs** [thoughtram/angular-zippy#1]
Hello,

Following the readme of this project I faced some problems.
Don't have time to investigate further so just for your info :)

_Errors:_
ModuleEvaluationError: $defineProperty is not a function ( traceur )
errs.join is not a function ( traceur )

_Steps to reproduce:_

git clone https://github.com/thoughtram/angular-zippy.git
cd angular-zippy
npm i && npm i -g gulp
gulp play
-> errors

_Node & NPM:_
node -v && npm -v
v4.2.1
3.3.9

grtz

**Comment by tobciu** [comment]
same problem

```
/home/vagrant/node/angular-zippy$ gulp play
[13:05:25] Using gulpfile /home/vagrant/node/angular-zippy/gulpfile.js
[13:05:25] Starting 'js'...
[13:05:25] Starting 'html'...
[13:05:25] Starting 'angular2'...
[13:05:25] 'angular2' errored after 84 ms
[13:05:25] ModuleEvaluationError: undefined is not a function
    at System.registerModule.__moduleName (/home/vagrant/node/angular-zippy/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:727:18)
 loaded by traceur@0.0.88/src/runtime/runtime-modules.js
[13:05:25] Plumber found unhandled error:
 TypeError in plugin 'gulp-traceur'
Message:
    undefined is not a function
Details:
    fileName: /home/vagrant/node/angular-zippy/src/hello
[13:05:25] Plumber found unhandled error:
 TypeError in plugin 'gulp-traceur'
Message:
    undefined is not a function
Details:
    fileName: /home/vagrant/node/angular-zippy/src/zippy
[13:05:25] Finished 'js' after 120 ms
[13:05:25] Finished 'html' after 114 ms
```

**Comment by ghost** [comment]
Got errors as well
[14:22:05] Using gulpfile d:\repositories\git\angular-zippy\gulpfile.js
[14:22:05] Starting 'js'...
[14:22:05] Starting 'html'...
[14:22:05] Starting 'angular2'...
[14:22:05] 'angular2' errored after 160 ms
[14:22:05] ModuleEvaluationError: $createPrivateName is not a function
    at d:\repositories\git\angular-zippy\node_modules\systemjs-builder\node_modules\traceur\bin\traceur.js:727:18
 loaded by traceur@0.0.88/src/runtime/runtime-modules.js
[14:22:05] Plumber found unhandled error:
 TypeError in plugin 'gulp-traceur'
Message:
    $getOwnPropertyDescriptor is not a function
Details:
    fileName: d:\repositories\git\angular-zippy\src\hello
[14:22:05] Plumber found unhandled error:
 TypeError in plugin 'gulp-traceur'
Message:
    $getOwnPropertyDescriptor is not a function
Details:
    fileName: d:\repositories\git\angular-zippy\src\zippy
[14:22:05] Finished 'js' after 254 ms
[14:22:05] Finished 'html' after 245 ms
